ARG BASE_IMAGE_SUFFIX

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster${BASE_IMAGE_SUFFIX} AS builder
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV NO_DOCKER 1
ENV IN_DOCKER 1

RUN apt update && apt install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*
# For compile Less style files in pre-build stage
RUN apt-get update \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash \
    && apt-get install -y nodejs

WORKDIR /src
COPY ./ /src/
