.PHONY: dev
dev:
	npm run start

.PHONY: vendor
vendor:
	npm install

.PHONY: dist
dist:
	npm run build

.PHONY: format
format:
	npm run format

.PHONY: lint
lint:
	npm run lint

.PHONY: test-cov
test-cov:
	npm run test:cov

.PHONY: test
test:
	npm run test
