"""Add orgCityId in Need table

Revision ID: 0e204d33f267
Revises: 96dfc07259e3
Create Date: 2022-04-23 20:21:49.812467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e204d33f267'
down_revision = '96dfc07259e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Needs', sa.Column('OrgCityId', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_needs_cities', 'Needs', 'Cities', ['OrgCityId'], ['Id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_needs_cities', 'Needs', type_='foreignkey')
    op.drop_column('Needs', 'OrgCityId')
    # ### end Alembic commands ###
