"""Mark Needs.OrgTypeId to be nullable

Revision ID: 5c9e866e291f
Revises: c6121f2eea8e
Create Date: 2022-05-08 10:54:44.668586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c9e866e291f'
down_revision = 'c6121f2eea8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Needs', 'OrgTypeId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Needs', 'OrgTypeId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
