"""Add new fields to Need

Revision ID: 841e44d933ee
Revises: 0e204d33f267
Create Date: 2022-04-24 11:10:31.389247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '841e44d933ee'
down_revision = '0e204d33f267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Needs', sa.Column('OrgRegCode', sa.Text(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Needs', 'OrgRegCode')
    # ### end Alembic commands ###
