.PHONY: dev
dev:
	$(MAKE) -C app dev

.PHONY: vendor
vendor:
	$(MAKE) -C app vendor

.PHONY: dist
dist:
	$(MAKE) -C app dist

.PHONY: format
format:
	$(MAKE) -C app format

.PHONY: lint
lint:
	$(MAKE) -C app lint

.PHONY: test-cov
test-cov:
	$(MAKE) -C app test-cov

.PHONY: test
test:
	$(MAKE) -C app test

.PHONY: db-migrate-up
db-migrate-up:
	$(MAKE) -C app db-migrate-up

.PHONY: db-init-data
db-init-data:
	$(MAKE) -C app db-init-data
