CREATE TABLE NeedNotes
(
	NeedId bigint NOT NULL,
	NoteId bigint NOT NULL,
	CONSTRAINT PK_NeedNotes PRIMARY KEY CLUSTERED (NeedId, NoteId),
	CONSTRAINT FK_NeedNotes_Needs FOREIGN KEY (NeedId) REFERENCES Needs (Id) ON DELETE CASCADE,
	CONSTRAINT FK_NeedNotes_Notes FOREIGN KEY (NoteId) REFERENCES Notes (Id) ON DELETE CASCADE
)
